### ISSUE TITLE
https://appr.tc expired certificate

### ISSUE THREAD

**Issue by homi06** [webrtc/apprtc#585]
**Browsers and versions affected**
Chrome v70

**Description**
https://appr.tc has expired certificate

**Steps to reproduce**
access https://appr.tc

**Expected results**
Valid certificate

**Actual results**
Expired certificate

**Comment by thiagompadilha** [comment]
Yes, it seems defeated. Any prediction of return?

**Comment by juberti** [comment]
@MirkoBonadei

**Comment by juberti** [comment]
@ErikHellman

**Comment by remyasics** [comment]
Will it be updated soon?

**Comment by remyasics** [comment]
Any restrictions to use this service when the app goes live
Like any certificate validation or anything like that?

**Comment by remyasics** [comment]
How long will the renewal of certificate lasts .

**Comment by KaptenJansson** [comment]
Fixed. There was a bug in UI for the verification of the CNAME record. It's now rectified.

**Comment by KaptenJansson** [comment]
Also, please do not use this for any type of production services, it's not under SLA or active development.

**Comment by remyasics** [comment]
I am still getting cert path validation exception.Not getting the service.

**Comment by remyasics** [comment]
Any one faces the above exception even now?

**Comment by remyasics** [comment]
> Yes, it seems out of date. Any prediction of return?

is it solved now after fixing the bug?

**Comment by homi06** [comment]
> > Yes, it seems out of date. Any prediction of return?
> 
> is it solved now after fixing the bug?

It fixed now

**Comment by thiagompadilha** [comment]
Hi everyone, this is working. One hour ago a console error persisted when using "/join/channel" and some ICE server error logs.

But now everything is working.
